export interface Patient {
    id: number;
    patientExternalId: string;
    cnamNumber: string;
    lastName: string;
    firstName: string;
    maidenName: string;
    gender: string;
    civility: string;
    birthDate: Date;
    profession: string;
    maritalStatus: string;
    numberOfChildren: number;
    address: string;
    cityId: number;
    country : number;
    cellPhone1: string;
    cellPhone2: string;
    email: string;
    idcardType:string;
    idCardNumber: string;
    motherFirstName: string;
    motherLastName: string;
    motherProfession: string;
    correspondant: string;
    correspondantCellPhone: string;
    emergencyContact1: string;
    emergencyContact2: string;
    insurances;
    // deathDate: Date;
    //picture: string;
    // country: number;
    // emailStop: string;
    // smsStop: string;
    // vaccinationProtocol: string;
}
